#!/usr/bin/perl

opendir (DIR, ".") or die "cannot read directory";
@dircontents = grep !/^\.\.?$/, readdir(DIR);
closedir(DIR);

if (-e "sequest.params") {
} else {
	die "ERROR: cannot find sequest.params!\n\n";
}

for ($i = 0; $i < scalar @dircontents; ++$i) {
    if (-d $dircontents[$i]) {
   	push (@dirs, $dircontents[$i]);
    }
}


print scalar @dirs . " directories\n";

$cmd = "";

#system ("find band* -name \'sequest*\' -exec \"rm\" {} \\;");


for ($i = 0; $i < scalar @dirs; ++$i) {
	system("cp sequest.params $dirs[$i]");
	chdir("$dirs[$i]");
#	print "\n$dirs[$i]\n";
#	system("DTASelect2 $ARGV[0]");
	print "$i of " . scalar @dirs . "\n";
	system("pwd");	
        system("DTASelect $ARGV[0]");
	chdir("..");
}
  	             


