#!/usr/local/bin/perl
#-------------------------------------
#	IonQuest,
#	(C)1997-2000 Harvard University
#	
#	W. S. Lane/C. M. Wendl
#
#	v3.1a
#	
#	licensed to Finnigan
#-------------------------------------


################################################
# find and read in standard include file
{

	$0 =~ m!(.*)\\([^\\]*)$!;
	do ("$1/development.pl");
	my $path = $0;
	$path =~ s!\\!/!g;
	$path =~ s!^(.*)/[^/]+/.*$!$1/etc!;
	unshift (@INC, "$path");
	require "microchem_include.pl";
	require "microchem_form_defaults.pl";
	require "status_include.pl";
	require "html_include.pl";
}
################################################

use Win32::ODBC;

# ionquest.pl: culls a directory for redundant DTAs.
# takes as input two directories: one to be operated upon (dir),
# the other as a reference (refdir).
# compares all DTAs in dir with all DTAs in refdir (using compare_dtas.exe),
# whenever a match of $reqmatch percent or more is found, deletes the DTA from dir.
# shows list of DTAs to delete and asks for confirmation before proceeding (in web mode only)

# How to use with other Perl scripts:
# -----------------------------------
# Arguments:
# dir - Fill in with the name of the trial sequest directory.
# refdir - Specifify one sequest reference directory.  Leave this blank if you want to compare to a
#          list of default reference directories, specified as @REFDIRS in michrochem.var.pl.
# autorefdir - If set, 'refdir' argument will be ignored, and ionquest will compare the given directory
#		   to the directory generated by the previous (based on run #) run on the same instrument.
# compare - If you are running IonQuest from outside and need it to do any processing, you should always 
#			set this to "1" so that Ionquest skips the default form.
# delete_matches - Toggles between 'Writing the checkbox state after processing to $ionquestlog and
#                  'Deleting the matches above the Threshold to Select.' "1" is for deleting, "0" is for
#                  checkboxes.

# Note to outside callers: the $ionquestlog file will only be written correctly if tables are set to be displayed.

# default settings may be edited in microchem_form_defaults.pl

## 6/7/2000 Added new radio buttons to allow user to show all matches or just those that
## are checked as above the selected percent threshold.  Code has been added in the two sub 
## functions show_matches_mass and show_matches_prec, as well as the main below. -- Lea

## 6/13/00 Tightened up the layout for the two main pages.  Also, the file $ionquestlog,
## which contains a list of all of the dta's that are pre-checked, is written to the local dir.
## Added the display of peptide sequences for all dta's with out files. -- P. Djeu

## 6/30/00 Added the dynamic checkboxes feature to dta_vcr -- P. Djeu

## 7/7/00 Added the option to use compare_dtas.exe or muquest.exe as the filter.

## 8/22/00 Rewrote the creation of $ionquestlog.  Now it includes only the best match for each selected dta.  The
## 'Write List' button uses a hidden form element for each dta to find its match (these hidden elements are of the form
## <input type="hidden" name="[dta name],[mass|prec]" value="[matching ref dta name],[this ref dta's %match]">.

## 11/15/01 SDR. Added qtfRefDir as argument to allow for QTF Convert to change ref directory when calling this program

##################################################################################################################
# 6/16/00 P.Djeu
# @dtavcr_links is used as input for dta_vcr.pl (via a tempfile -- see sub dta_vcr_code().  This array contains
# all of the links verbatim from the % Match column on the tables page.  The user can now thumb through all of
# these links rather than view them one at a time.
# 6/23/00
# @dtavcr_infos is used as input for dta_vcr.pl (via a tempfile -- see sub dta_vcr_code().  This array contains
# line by line of the tables and is used in tandem with @dtavcr_links (i.e. there corresponding indices represent
# the same elment in the table.
# 7/3/00
# @dtavcr_include_ifs is used as input for dta_vcr.pl (via a tempfile -- see sub dta_vcr_code().  This array contains
# a listing of all of the dtas in the order they appear in the two tables.  The 'selected' form field contains a list
# of dta names that will be shown when DTA VCR is run.  Each entry is in the form, 'dta_filename' . '[mass | prec]'
# to indicate which table the entry is in.
# 8/22/00
# %dtas_to_write is a hash of the best dta pair matches.  The hash is of the form:
# key =   [sample dta name],[mass|prec]
# value = [bestmatch reference dta name],[%match]
@dtavcr_links = ();
@dtavcr_infos = ();
@dtavcr_include_ifs= ();
%dtas_to_write = ();

&cgi_receive;
if (($FORM{'show_best_only'} == 1) && !($FORM{"should_delete"}))
{
	&best_to_dtavcr;
	exit(0);
}

&do_update_text if ($FORM{"update_text"});	# Quick execution to prevent waits -- 6/22/00 P.Djeu

$dir = $FORM{"directory"};
$autorefdir = $FORM{"autorefdir"};
$refdirs = $FORM{"refdir"};
$reqmatch = (defined $FORM{"percentage"}) ? $FORM{"percentage"} : $DEFS_IONQUEST{"Percent Match Threshold"};
$tolerance = (defined $FORM{"tolerance"}) ? $FORM{"tolerance"} : $DEFS_IONQUEST{"Mass Tolerance"};
$sortby = (defined $FORM{"sort"}) ? $FORM{"sort"} : $DEFS_IONQUEST{"Sort comparison list by"};
$delete_matches = (defined $FORM{"delete_matches"}) ? $FORM{"delete_matches"} : ($DEFS_IONQUEST{"Behavior"} eq "Delete matches");
$qtfRefDir = $FORM{"qtfRefDir"};

# couple of defaults...
$MAX_RUNS_TO_SKIP = 10;
$DEFAULT_IQ_PERCENTAGE = 40;

if (defined $FORM{'defaultpercentage'}) {
	$reqmatch = $DEFAULT_IQ_PERCENTAGE;
}

######## added by lea 6/7/00 buttons to allow the user to show all matches or just those which are checked.
######## modified by Peter 6/9/00 to enable a form variable defined display_threshold
$show_all = (defined $FORM{"show_all"}) ? $FORM{"show_all"} : ($DEFS_IONQUEST{"Show"} eq "All");
# Display all matches (display_threshold = 0) if no threshold is given
$display_threshold = (defined $FORM{"display_threshold"}) ? $FORM{"display_threshold"} : "0";
$filter = (defined $FORM{"filter"}) ? $FORM{"filter"} : "compare_dtas";

# checkboxes
$comparemass = ($FORM{"defined_comparemass"} || (defined $FORM{"comparemass"})) ? $FORM{"comparemass"} : ($DEFS_IONQUEST{"Compare MH+"} eq "yes");
$compareprec = ($FORM{"defined_compareprec"} || (defined $FORM{"compareprec"})) ? $FORM{"compareprec"} : ($DEFS_IONQUEST{"Compare Precursor"} eq "yes");

if ($autorefdir) {
	$refdirs = getReferenceDirectory($dir);
}
@refdirs = ($refdirs =~ /,/) ? split(/,\s*/, $refdirs) : ($refdirs);
if (!defined $refdirs) {
	@refdirs = @REFDIRS;
	$refdirs = join(", ",@refdirs);
}

$multiple_refdirs = (scalar(@refdirs) > 1) ? "1" : "0";

&MS_pages_header("IonQuest","4040A0");
print "<HR>";

&quick_delete if ($FORM{"quick_delete"});
&output_form unless ($FORM{"compare"});

# search for matches and either delete them or output a table

&watch_over_me;			# includes control for this app on the sequest status page.

$fancyname = &get_fancyname($dir);

chdir "$seqdir/$dir" || &error("Directory $dir inaccessible.<P>$!");

&error("You may not compare $fancyname with itself!") if (grep /^$dir$/, @refdirs);
# P. Djeu - Error check
if (($show_all == 0) && ($display_threshold > $reqmatch)) {
	&error("'Threshold to Select' should be greater than 'Show: Matches Above %'.  Otherwise, unseen files may be deleted.");
}

opendir (DIR, ".") or &error("Cannot read directory $dir: $!\n");
@dtas = grep { /\.(dta)$/ } readdir(DIR);
closedir DIR;

# CreateDTA once had checkboxes to allow iterating runs on user-defined reference directories, but we've
# since reduced it to its present behavior where it always just uses the "default" refdirs (@REFDIRS).
# most likely no other programs utilize this functionality, so the following code is pretty obscure
@refdtas = ();
foreach $refdir (@refdirs) {
	opendir (REFDIR, "$seqdir/$refdir") or &error("Cannot read directory $refdir: $!\n");
	push(@refdtas, map "$seqdir/$refdir/$_", grep { /\.(dta)$/ } readdir(REFDIR));
	closedir REFDIR;
}

# this block loops through all DTAs and reference DTAs, finds all matches and
# stores relevant information in the arrays @massmatches and @precmatches (arrays of hashes)

@massmatches = ();
@precmatches = ();

# Added a progress bar.  See load_java_toggle progress() for the disappearing text routine. 7/10/00 P.Djeu
$browser = $FORM{"browser"};
if ($browser eq "IE") {	# NN does not currently support disappearing text (namely the innerHTML property)
	$| = 1;
	$i = 0;
	$next_percent = 0.05;
	$max_i = scalar(@dtas);
	print qq(<span id="progress"><span class="smallheading">Filtering Progress:</span>\n);
	print qq(<pre><b>0%                               100%\n);
}

foreach $dta (@dtas)
{
	# Added 7/10/00 P. Djeu.
	if ($browser eq "IE") {
		$i++;
		if (($i / $max_i) >= $next_percent) {
			$next_percent += 0.05;
			print ". ";
		}
	} # End 7/10/00

	# find mass and precursor of $dta
	open (FILE, "<$dta");
	$mhplus_z = <FILE>;
	close FILE;
	chomp $mhplus_z;
	($mhplus, $z) = split (' ', $mhplus_z);
	$mass = &precision ($mhplus - $Mono_mass{"Hydrogen"}, 2, 4, " ");
	$prec = &precision ( (($mhplus - $Mono_mass{"Hydrogen"}) / $z) + $Mono_mass{"Hydrogen"}, 2, 4, " ");

	@mmatches = ();
	@pmatches = ();
	
	foreach $refdta (@refdtas)
	{
		# compare masses, if within tolerance, then do $compare_dtas
		# find mass of $refdta
		open (FILE, "$refdta");
		$mhplus_z = <FILE>;
		close FILE;
		chomp $mhplus_z;
		($mhplus, $z) = split (' ', $mhplus_z);
		$refmass = &precision ($mhplus - $Mono_mass{"Hydrogen"}, 2, 4, " ");
		$refprec = &precision ( (($mhplus - $Mono_mass{"Hydrogen"}) / $z) + $Mono_mass{"Hydrogen"}, 2, 4, " ");

		if ((abs($mass - $refmass) <= $tolerance) && $comparemass)	# if masses match within tolerance
		{
			# Modified 7/10/00 by P.Djeu
			if ($filter eq "compare_dtas") {
				$result = `$compare_dtas ShowIntensity=1 Dta=$seqdir/$dir/$dta  Dta=$refdta`;
			} elsif ($filter eq "muquest") {
				$result_mu = `$muquest $seqdir/$dir/$dta  $refdta 0`;
				# cut off the offset value
				$result_mu =~ s/\s\d+$//;
				$result_mu = &precision($result_mu, 3);
			} elsif ($filter eq "both") {
				$result = `$compare_dtas Dta=$seqdir/$dir/$dta  Dta=$refdta`;
				$result_mu = `$muquest $seqdir/$dir/$dta  $refdta 0`;
				#chomp $result_mu;
				# cut off the offset value
				$result_mu =~ s/\s\d+$//;
				$result_mu = &precision($result_mu, 3);
			}
			chomp $result;
			# End 7/10/00 (pcd)
			# SDR: 10/22/02 Done for intenisty values, source code added a new flag for this as well.
			($result, $inten1, $inten2) = $result =~ /^(\d+)% ions.*\((\d+)\), \((\d+)\)/gs; # just the percentage (without %), and the intensities

			%thismatch = (
				refdta	=> $refdta,
				result	=> $result,
				result_mu	=> $result_mu,
				refmass	=> $refmass,
				inten1 => $inten1,
				inten2 => $inten2
			);
			push(@mmatches, { %thismatch } );
		} 
		elsif ((abs($prec - $refprec) <= $tolerance) && $compareprec)		# if precursors match within tolerance
		{
			# Modified 7/10/00 by P.Djeu
			if ($filter eq "compare_dtas") {
				$result = `$compare_dtas ShowIntensity=1 Dta=$seqdir/$dir/$dta  Dta=$refdta`;
			} elsif ($filter eq "muquest") {
				$result_mu = `$muquest $seqdir/$dir/$dta  $refdta 0`;
				# cut off the offset value
				$result_mu =~ s/\s\d+$//;
				$result_mu = &precision($result_mu, 3);
			} elsif ($filter eq "both") {
				$result = `$compare_dtas Dta=$seqdir/$dir/$dta  Dta=$refdta`;
				$result_mu = `$muquest $seqdir/$dir/$dta  $refdta 0`;
				#chomp $result_mu;
				# cut off the offset value
				$result_mu =~ s/\s\d+$//;				
				$result_mu = &precision($result_mu, 3);
			}
			chomp $result;
			# End 7/10/00 (pcd)

			# SDR: 10/22/02 Done for intenisty values, source code added a new flag for this as well.
			($result, $inten1, $inten2) = $result =~ /^(\d+)% ions.*\((\d+)\), \((\d+)\)/gs; # just the percentage (without %), and the intensities

			%thismatch = (
				refdta	=> $refdta,
				result	=> $result,
				result_mu	=> $result_mu,
				refprec	=> $refprec,
				inten1 => $inten1,
				inten2 => $inten2
			);
			push(@pmatches, { %thismatch } );
		}
	}
	# find related files for each match
	if (@mmatches)
	{
		# sort matches in descending order by comparison result
		@mmatches = sort { $b->{"result"} <=> $a->{"result"} } @mmatches;
		%matchinfo = (
			dta		=> $dta,
			mass		=> $mass,
			matches	=> [ @mmatches ] 
		);
		push(@massmatches, { %matchinfo } );
	}
	if (@pmatches)
	{
		# sort matches in descending order by comparison result
		@pmatches = sort { $b->{"result"} <=> $a->{"result"} } @pmatches;
		%matchinfo = (
			dta		=> $dta,
			prec		=> $prec,
			matches	=> [ @pmatches ]
		);
		push(@precmatches, { %matchinfo } );
	}
}

# Added 7/10/00 P. Djeu.
if ($browser eq "IE") {
	print "</b></pre></span>\n\n";
	&load_java_toggle_progress;
}

if ($delete_matches) {
	&delete_matches;
} else {
	&output_table;
}

# this is unnecessary, but just to make things perfectly clear:
exit;


###########################      Begin Table Display code     ############################################################

##------------------------------------------------------------------------------------------------------------------------
##------------------------------------------------------------------------------------------------------------------------
sub show_matches_mass {
	my ($show_all_flag, $disp_thresh_met, $dtavcr_link, $dtavcr_info, $dtavcr_info2, $row_color);

	foreach $matchinforef (@massmatches)
		{			
			%matchinfo = %$matchinforef;
			$dta = $matchinfo{"dta"};
			$mass = $matchinfo{"mass"};
			$mass =~ s/\s//g;	# Get rid of leading space 6/26/00 P. Djeu
			if (@$related{$dta}) { 
				@related = @$related{$dta};
			} else {
				@related = &find_related($dta);
				$related{$dta} = [ @related ];
			}
			@matches = @{$matchinfo{"matches"}};

			$bestmatch = $matchinfo{"matches"}->[0]->{"result"};

			$nummatches = @matches;
			
			#######    Added 6/7/2000 by Lea to check new radio options
			#######    P. Djeu 6/11/00 changed to display entries above display_threshold and check entries above
			#######    $reqmatch
			$show_all_flag = $show_all;			# get parameters from radio options

			# Only check entries by default when they are above the reqmatch threshold
			if ($bestmatch >= $reqmatch) {
				$checked = " checked";
			} else {
				$checked = "";
			}

			# If user does not want to show all files, show only the entries above the display_threshold
			if ($show_all_flag != 1) {
				$disp_thresh_met = ($bestmatch >= $display_threshold) ? "1" : "0";
			}

			# If show_all was selected on the Ionquest main page, show everything regardless
			# Otherwise, check to make sure it meets the display_threshold
			if(($show_all_flag == 1) || ($disp_thresh_met == 1))
			{
			# Alternate the row color
			$row_color = ($row_color eq "#ffffff") ? "#e8e8e8" : "#ffffff";

			my ($prefix, $charge) = $dta =~ m!$dtaPrefixChargeRE!;

			# Added 8-22-00 P.Djeu
			# Log the checked dtas with the reference dtas they correspond with
			if ($bestmatch >= $reqmatch) {
				($inten1, $inten2) = ($matchinfo{"matches"}->[0]->{"inten1"}, $matchinfo{"matches"}->[0]->{"inten2"});
				$bestrefdta = $matchinfo{"matches"}->[0]->{"refdta"};
				$bestrefdta =~ s/$seqdir\/$refdirs\///o;
				$dtas_to_write{"$dta,mass"} = "$bestrefdta,$bestmatch,$inten1,$inten2";
			}
			# Used with 'Write List' button
			print qq(<input type="hidden" name="$dta,mass" value="$bestrefdta,$bestmatch,$inten1,$inten2">);
			# End 8-22-00
			
			# Try to open .out file and read the first peptide sequence.  6/13/00, P. Djeu
			my $outfile = "$prefix\.$charge\.out";
			my $pep_seq = &get_peptide_sequence("$seqdir/$dir/$outfile");
			my $first_char;
			my ($result_mu, $result_mu2);

			print <<EOF;
<tr bgcolor=$row_color>
	<td rowspan=$nummatches nowrap>
		<table cellspacing=0 cellpadding=0 border=0><tr><td>
		<input type=checkbox name="$dta" value="delete"$checked></td><td nowrap>
EOF
			# 6/12/00 changed formatting for tighter look -- P. Djeu
			# All of first <td> must be on single HTML line to look right, so print ""'s are used rather than print <<EOF
			print "<span class=\"smalltext\">$prefix\|<a href=\"$fuzzyions?Dta=$seqdir/$dir/$dta\" target=\"_blank\" title=\"Goto FuzzyIons\">"
				  ."<span style=\"color:#008000\">$charge</span></a>";

				foreach $relfile (sort @related)
				{
					unless ($relfile eq $dta)	# $dta is also part of @related, so don't print it twice
					{
						if ($relfile =~ /\.dta$/) {	# if $relfile is a DTA
							$link = "|<a href=\"$fuzzyions?Dta=$seqdir/$dir/$relfile\" target=\"_blank\" title=\"Goto FuzzyIons\">";
							$endlink = "</a>";
							# Trim DTA to just charge
					        ($relfile) = ($relfile =~ m!$dtaChargeRE!);
						} elsif ($relfile =~ /\.out$/) {
							$link = $endlink = "";		# no link if it's an OUT
							$relfile = "|o";			# Trim OUT's to just the symbol o
						} elsif ($relfile =~ /\.zta$/) {
							$link = $endlink = "";		# no link if it's a ZTA
							$relfile = "|z";			# Trim ZTA's to just the symbol z
						} else {
							$link = "|";
							$endlink = "";
							$relfile =~ s/$prefix\.//;	# Print entire extension
						}
					print "$link$relfile$endlink";

					}
				}
			print "&nbsp;";
			
			# Form tag already provided by DTA VCR
			$dtavcr_info = qq(<table cellspacing=0 cellpadding=0 border=0><tr><td rowspan=2 valign="middle"><input type="checkbox" name="box" value="yes"><input type="hidden" name="id" value="$dta"><input type="hidden" name="tableID" value="mass">&nbsp;);
			$dtavcr_info .= qq(<td align="center"><span class="smallheading">Sample</span><td align="center"><span class="smallheading">MH+</span>);
			$dtavcr_info .= qq(<td align="center"><span class="smallheading">Match</span><td align="center"><span class="smallheading">MH+</span><td align="center"><span class="smallheading">Ref</span>);

			if ($pep_seq ne "0") {
				# Print peptide sequence in the format seen in Sequest Summary
				# For example, the sequence 'R.GNPVPLR.V' would be printed (R)GNPVPLR
				($first_char, $pep_seq) = split (/\./, $pep_seq);
				# Make compatible with old .out files 6/27/00 P.Djeu
				if ($pep_seq eq "") {
					($first_char, $pep_seq) = ($first_char =~ m!\((.)\)(.*)!);
				}
				print <<EOF;
<a href="showout.pl?OutFile=$seqdir/$dir/$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp;
EOF

				$dtavcr_info .= qq(<tr><td><span class="smalltext"><a href="$fuzzyions?Dta=$seqdir/$dir/$dta" target="_blank" title="Goto FuzzyIons">$dta</a>&nbsp;);
				$dtavcr_info .= qq(<a href="showout.pl?OutFile=$seqdir/$dir/$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp</span>);
			} else {
				$dtavcr_info .= qq(<tr><td><span class="smalltext"><a href="$fuzzyions?Dta=$seqdir/$dir/$dta" target="_blank" title="Goto FuzzyIons">$dta</a>&nbsp;</span>);
			}

		print <<EOF;
</span></td></tr></table></td>
	<td align="center" rowspan=$nummatches><span class="smalltext">&nbsp;$mass&nbsp;</span></td>
EOF
				$dtavcr_info .= qq(<td><span class="smalltext">&nbsp;$mass&nbsp;</span>);

				$firstrow = 1;
				foreach $matchref (@matches)
				{
					$dtavcr_info2 = $dtavcr_info;

					$refdta = $matchref->{"refdta"};
					# P.Djeu 6/12/00 -- Shortened dta file name to compress layout
					# 6/20/00 Protein sequence also displayed for reference dta's
					# 6/23/00 Handles multiple ref directories
					if ($multiple_refdirs) {
						($shortrefdta = $refdta) =~ s/^$seqdir\///;				# Truncate less for clarity
					} else {
						($shortrefdta = $refdta) =~ s/^$seqdir\/$refdirs\///;	# Truncate more if unambiguous
					}
					($outfile = $refdta) =~ s/\.dta$/\.out/;
					$pep_seq = &get_peptide_sequence("$outfile");
					$shortrefdta =~ s/\.dta$//;

					$refmass = $matchref->{"refmass"};
					$refmass =~ s/\s//g;		# 6/26/00 P. Djeu -- Gets rid of leading space
					$result  = $matchref->{"result"};

					if ($filter eq "both" || $filter eq "muquest") {
						$result_mu = $matchref->{"result_mu"};
						if ($result_mu < 1.48) {
							$result_mu2 = $result_mu * 13.5;
						} else {
							$result_mu2 = ((log $result_mu) / (log 7.21)) * 100;
						}
						$result_mu2 = &precision($result_mu2, 0);
						$result_mu2 = ($result_mu2 > 100) ? 100 : $result_mu2;
					}
					print "<tr bgcolor=$row_color>\n" unless ($firstrow);

					# 6/16/00 P.Djeu Enabled use of dta vcr on the files shown on the page.
					$dtavcr_link = "$thumbnails?Dta=$seqdir/$dir/$dta&Dta=$refdta";
					push (@dtavcr_links, "$dtavcr_link");
					push (@dtavcr_include_ifs, "$dta" . "_mass");

					# Color code the % matches
					if ($filter eq "muquest") {
						print qq(<td align="center"><span class="smalltext">&nbsp;<span style="color:#ff0000">$result_mu2\%</span>&nbsp;$result_mu</span>&nbsp;</span></td>);
						$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#ff0000">&nbsp;$result_mu2\%</span><span class="smalltext">&nbsp;$result_mu&nbsp;</span>);
					} elsif ($result >= $reqmatch) {
						print qq(<td align="center"><span class="smalltext">&nbsp;<a href="$dtavcr_link" target="_blank" title="Show Thumbnails"><span style="color:#008000">$result\%</span></a>&nbsp;</span></td>);
						if ($filter eq "both") {
							print qq(<td align="center"><span class="smalltext">&nbsp;<span style="color:#ff0000">$result_mu2\%</span>&nbsp;$result_mu</span>&nbsp;</span></td>);
						}
						$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#008000">&nbsp;$result\%&nbsp;</span>);
					} else {	# $result < $reqmatch
						print qq(<td align="center"><span class="smalltext">&nbsp;<a href="$dtavcr_link" target="_blank" title="Show Thumbnails"><span style="color:#000000">$result\%</span></a>&nbsp;</span></td>);
						if ($filter eq "both") {
							print qq(<td align="center"><span class="smalltext">&nbsp;<span style="color:#ff0000">$result_mu2\%</span>&nbsp;$result_mu</span>&nbsp;</span></td>);
							$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#000000">&nbsp;$result\%&nbsp;</span><span class="smalltext" style="color:#ff0000">$result_mu2\%</span><span class="smalltext">&nbsp;$result_mu&nbsp;</span>);
						} else {
							$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#000000">&nbsp;$result\%&nbsp;</span>);
						}
					}
					
					print <<EOF;
<td align="center"><span class="smalltext">&nbsp;$refmass&nbsp;</span></td>
<td nowrap><span class="smalltext">&nbsp;<a href="$fuzzyions?Dta=$refdta" target="_blank" title="Goto FuzzyIons">$shortrefdta</a>&nbsp;
EOF
					$dtavcr_info2 .= qq(<td><span class="smalltext">&nbsp;$refmass&nbsp;</span><td><span class="smalltext">&nbsp;<a href="$fuzzyions?Dta=$refdta" target="_blank" title="Goto FuzzyIons">$shortrefdta</a>&nbsp;);

					if ($pep_seq ne "0") {
						# Print peptide sequence in the format seen in Sequest Summary
						# For example, the sequence 'R.GNPVPLR.V' would be printed (R)GNPVPLR
						($first_char, $pep_seq) = split (/\./, $pep_seq);
						# Make compatible with old .out files 6/27/00 P.Djeu
						if ($pep_seq eq "") {
							($first_char, $pep_seq) = ($first_char =~ m!\((.)\)(.*)!);
						}
						print <<EOF;
<a href="showout.pl?OutFile=$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp;</span></td></tr>
EOF
						
						$dtavcr_info2 .= qq(<a href="showout.pl?OutFile=$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp;</span></table>);
					} else {
						print "</span></td></tr>\n";
						$dtavcr_info2 .= qq(</span></table>);
					}
					
					# Used for dta_vcr, this triggers the dynamic checkbox feature by calling Javascript in Ionquest
					$dtavcr_info2 .= qq(\\n<script language="Javascript">\\n<!--\\nparent.parent.opener.check_box();\\n//--></script>);

					push (@dtavcr_infos, $dtavcr_info2);

					$firstrow = 0;
				}
			}	
		}
		print "</table>\n";
}


##------------------------------------------------------------------------------------------------------------------------
##------------------------------------------------------------------------------------------------------------------------

sub show_match_prec{	
	my ($show_all_flag, $disp_thresh_met, $dtavcr_link, $dtavcr_info, $dtavcr_info2, $row_color);

	foreach $matchinforef (@precmatches){

			%matchinfo = %$matchinforef;
			$dta = $matchinfo{"dta"};
			$prec = $matchinfo{"prec"};
			$prec =~ s/\s//g;	# Get rid of leading space 6/26/00 P. Djeu

			if (@$related{$dta}) { 
				@related = @$related{$dta};
			} else {
				@related = &find_related($dta);
				$related{$dta} = [ @related ];
			}
			@matches = @{$matchinfo{"matches"}};

			$bestmatch = $matchinfo{"matches"}->[0]->{"result"};
			
			$nummatches = @matches;

			#######    Added 6/7/2000 by Lea to check new radio options
			#######    P. Djeu 6/11/00 changed to display entries above display_threshold and check entries above
			#######    $reqmatch
			$show_all_flag = $show_all;			# get parameters from radio options

			# Only check entries by default when they are above the reqmatch threshold
			if ($bestmatch >= $reqmatch) {
				$checked = " checked";
			} else {
				$checked = "";
			}

			# If user does not want to show all files, show only the entries above the display_threshold
			if ($show_all_flag != 1) {
				$disp_thresh_met = ($bestmatch >= $display_threshold) ? "1" : "0";
			}

			# If show_all was selected on the Ionquest main page, show everything regardless
			# Otherwise, check to make sure it meets the display_threshold
			if(($show_all_flag == 1) || ($disp_thresh_met == 1))
			{
			# Alternate the row color
			$row_color = ($row_color eq "#ffffff") ? "#e8e8e8" : "#ffffff";

			my ($prefix, $charge) = $dta =~ m!$dtaPrefixChargeRE!;

			# Added 8-22-00 P.Djeu
			# Log the checked dtas with the reference dtas they correspond with
			if ($bestmatch >= $reqmatch) {
				($inten1, $inten2) = ($matchinfo{"matches"}->[0]->{"inten1"}, $matchinfo{"matches"}->[0]->{"inten2"});
				$bestrefdta = $matchinfo{"matches"}->[0]->{"refdta"};
				$bestrefdta =~ s/$seqdir\/$refdirs\///o;
				$dtas_to_write{"$dta,prec"} = "$bestrefdta,$bestmatch,$inten1,$inten2";
			}
			# Used with 'Write List' button
			print qq(<input type="hidden" name="$dta,prec" value="$bestrefdta,$bestmatch,$inten1,$inten2">);
			# End 8-22-00

			# Try to open .out file and read the first peptide sequence.  6/13/00, P. Djeu
			my $outfile = "$prefix\.$charge\.out";
			my $pep_seq = &get_peptide_sequence("$seqdir/$dir/$outfile");
			my $first_char;
			my ($result_mu, $result_mu2);

			print <<EOF;
<tr bgcolor=$row_color>
	<td rowspan=$nummatches nowrap>
		<table cellspacing=0 cellpadding=0 border=0><tr><td>
		<input type=checkbox name="$dta" value="delete"$checked></td><td nowrap>
EOF
			# 6/12/00 changed formatting for tighter look -- P. Djeu
			# All of first <td> must be on single HTML line to look right, so print ""'s are used rather than print <<EOF
			print "<span class=\"smalltext\">$prefix\|<a href=\"$fuzzyions?Dta=$seqdir/$dir/$dta\" target=\"_blank\" title=\"Goto FuzzyIons\">"
				  ."<span style=\"color:#008000\">$charge</span></a>";

				foreach $relfile (sort @related)
				{
					unless ($relfile eq $dta)	# $dta is also part of @related, so don't print it twice
					{
						if ($relfile =~ /\.dta$/) {	# if $relfile is a DTA
							$link = "|<a href=\"$fuzzyions?Dta=$seqdir/$dir/$relfile\" target=\"_blank\" title=\"Goto FuzzyIons\">";
							$endlink = "</a>";
							# Trim DTA to just charge
					        ($relfile) = ($relfile =~ m!$dtaChargeRE!);
						} elsif ($relfile =~ /\.out$/) {
							$link = $endlink = "";		# no link if it's an OUT
							$relfile = "|o";			# Trim OUT's to just the symbol o
						} elsif ($relfile =~ /\.zta$/) {
							$link = $endlink = "";		# no link if it's a ZTA
							$relfile = "|z";			# Trim ZTA's to just the symbol z
						} else {
							$link = "|";
							$endlink = "";
							$relfile =~ s/$prefix\.//;	# Print entire extension
						}
					print "$link$relfile$endlink";

					}
				}
			print "&nbsp;";

			# Form tag already provided by DTA VCR
			$dtavcr_info = qq(<table cellspacing=0 cellpadding=0 border=0><tr><td rowspan=2 valign="middle"><input type="checkbox" name="box" value="yes"><input type="hidden" name="id" value="$dta"><input type="hidden" name="tableID" value="prec">&nbsp;);
			$dtavcr_info .= qq(<td align="center"><span class="smallheading">Sample</span><td align="center"><span class="smallheading">Prec</span>);
			$dtavcr_info .= qq(<td align="center"><span class="smallheading">Match</span><td align="center"><span class="smallheading">Prec</span><td align="center"><span class="smallheading">Ref</span>);

			if ($pep_seq ne "0") {
				# Print peptide sequence in the format seen in Sequest Summary
				# For example, the sequence 'R.GNPVPLR.V' would be printed (R)GNPVPLR
				($first_char, $pep_seq) = split (/\./, $pep_seq);
				# Make compatible with old .out files 6/27/00 P.Djeu
				if ($pep_seq eq "") {
					($first_char, $pep_seq) = ($first_char =~ m!\((.)\)(.*)!);
				}
				print <<EOF;
<a href="showout.pl?OutFile=$seqdir/$dir/$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp;
EOF

				$dtavcr_info .= qq(<tr><td><span class="smalltext"><a href="$fuzzyions?Dta=$seqdir/$dir/$dta" target="_blank" title="Goto FuzzyIons">$dta</a>&nbsp;);
				$dtavcr_info .= qq(<a href="showout.pl?OutFile=$seqdir/$dir/$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp</span>);
			} else {
				$dtavcr_info .= qq(<tr><td><span class="smalltext"><a href="$fuzzyions?Dta=$seqdir/$dir/$dta" target="_blank" title="Goto FuzzyIons">$dta</a>&nbsp;</span>);
			}

		print <<EOF;
</span></td></tr></table></td>
	<td align="center" rowspan=$nummatches><span class="smalltext">&nbsp;$prec&nbsp;</span></td>
EOF
				$dtavcr_info .= qq(<td><span class="smalltext">&nbsp;$prec&nbsp;</span>);

				$firstrow = 1;
				foreach $matchref (@matches)
				{
					$dtavcr_info2 = $dtavcr_info;
					
					$refdta = $matchref->{"refdta"};
					# P.Djeu 6/12/00 -- Shortened dta file name to compress layout
					# 6/20/00 Protein sequence also displayed for reference dta's
					# 6/23/00 Handles multiple ref directories
					if ($multiple_refdirs) {
						($shortrefdta = $refdta) =~ s/^$seqdir\///;				# Truncate less for clarity
					} else {
						($shortrefdta = $refdta) =~ s/^$seqdir\/$refdirs\///;	# Truncate more if unambiguous
					}
					($outfile = $refdta) =~ s/\.dta$/\.out/;
					$pep_seq = &get_peptide_sequence("$outfile");
					$shortrefdta =~ s/\.dta$//;
					
					$refprec = $matchref->{"refprec"};
					$refprec =~ s/\s//g;		# 6/26/00 P. Djeu -- Gets rid of leading space
					$result  = $matchref->{"result"};

					if ($filter eq "both" || $filter eq "muquest") {
						$result_mu = $matchref->{"result_mu"};
						if ($result_mu < 1.48) {
							$result_mu2 = $result_mu * 13.5;
						} else {
							$result_mu2 = ((log $result_mu) / (log 7.21)) * 100;
						}
						$result_mu2 = &precision($result_mu2, 0);
						$result_mu2 = ($result_mu2 > 100) ? 100 : $result_mu2;
					}
					print "<tr bgcolor=$row_color>\n" unless ($firstrow);
					
					# 6/16/00 P.Djeu Enabled use of dta vcr on the files shown on the page.
					$dtavcr_link = "$thumbnails?Dta=$seqdir/$dir/$dta&Dta=$refdta";
					push (@dtavcr_links, "$dtavcr_link");
					push (@dtavcr_include_ifs, "$dta" . "_prec");

					# Color code the % matches
					if ($filter eq "muquest") {
						print qq(<td align="center"><span class="smalltext">&nbsp;<span style="color:#ff0000">$result_mu2\%</span>&nbsp;$result_mu</span>&nbsp;</span></td>);
						$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#ff0000">&nbsp;$result_mu2\%</span><span class="smalltext">&nbsp;$result_mu&nbsp;</span>);
					} elsif ($result >= $reqmatch) {
						print qq(<td align="center"><span class="smalltext">&nbsp;<a href="$dtavcr_link" target="_blank" title="Show Thumbnails"><span style="color:#008000">$result\%</span></a>&nbsp;</span></td>);
						if ($filter eq "both") {
							print qq(<td align="center"><span class="smalltext">&nbsp;<span style="color:#ff0000">$result_mu2\%</span>&nbsp;$result_mu</span>&nbsp;</td>);
						}
						$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#008000">&nbsp;$result\%&nbsp;</span>);
					} else {	# $result < $reqmatch
						print qq(<td align="center"><span class="smalltext">&nbsp;<a href="$dtavcr_link" target="_blank" title="Show Thumbnails"><span style="color:#000000">$result\%</span></a>&nbsp;</span></td>);
						if ($filter eq "both") {
							print qq(<td align="center"><span class="smalltext">&nbsp;<span style="color:#ff0000">$result_mu2\%</span>&nbsp;$result_mu&nbsp;</span></td>);
							$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#000000">&nbsp;$result\%&nbsp;</span><span class="smalltext" style="color:#ff0000">$result_mu2\%</span><span class="smalltext">&nbsp;$result_mu&nbsp;</span>);
						} else {
							$dtavcr_info2 .= qq(<td><span class="smalltext" style="color:#000000">&nbsp;$result\%&nbsp;</span>);
						}
					}

					print <<EOF;
<td align="center"><span class="smalltext">&nbsp;$refprec&nbsp;</span></td>
<td nowrap><span class="smalltext">&nbsp;<a href="$fuzzyions?Dta=$refdta" target="_blank" title="Goto FuzzyIons">$shortrefdta</a>&nbsp;
EOF
					$dtavcr_info2 .= qq(<td><span class="smalltext">&nbsp;$refprec&nbsp;</span><td><span class="smalltext">&nbsp;<a href="$fuzzyions?Dta=$refdta" target="_blank" title="Goto FuzzyIons">$shortrefdta</a>&nbsp;);

					if ($pep_seq ne "0") {
						# Print peptide sequence in the format seen in Sequest Summary
						# For example, the sequence 'R.GNPVPLR.V' would be printed (R)GNPVPLR
						($first_char, $pep_seq) = split (/\./, $pep_seq);
						# Make compatible with old .out files 6/27/00 P.Djeu
						if ($pep_seq eq "") {
							($first_char, $pep_seq) = ($first_char =~ m!\((.)\)(.*)!);
						}
						print <<EOF;
<a href="showout.pl?OutFile=$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp;</span></td></tr>
EOF

						$dtavcr_info2 .= qq(<a href="showout.pl?OutFile=$outfile" target="_blank" title="Goto Showout"><span style="color:#800000">($first_char)$pep_seq</span></a>&nbsp;</span></table>);
					} else {
						print "</span></td></tr>\n";
						$dtavcr_info2 .= qq(</span></table>);
					}

					# Used for dta_vcr, this triggers the dynamic checkbox feature by calling Javascript in Ionquest
					$dtavcr_info2 .= qq(\\n<script language="Javascript">\\n<!--\\nparent.parent.opener.check_box();\\n//--></script>);

					push (@dtavcr_infos, $dtavcr_info2);

					$firstrow = 0;
				}
			}
		}
		print "</table>\n";
}

##------------------------------------------------------------------------------------------------------------------------
##------------------------------------------------------------------------------------------------------------------------



sub output_table {

	&load_java_warning2();
	&load_java_update_text();

	print <<EOF;
EOF

	# sort array of matches according to user specifications

	@massmatches = sort { $a->{"dta"} cmp $b->{"dta"} } @massmatches
		if ($sortby eq "DTA Name");
	@massmatches = sort { $a->{"mass"} <=> $b->{"mass"} } @massmatches
		if ($sortby eq "DTA Mass (ascending)");
	@massmatches = sort { $b->{"mass"} <=> $a->{"mass"} } @massmatches
		if ($sortby eq "DTA Mass (descending)");
	@massmatches = sort { $a->{"matches"}->[0]->{"result"} <=> $b->{"matches"}->[0]->{"result"} } @massmatches
		if ($sortby eq "Match Percentage (ascending)");
	@massmatches = sort { $b->{"matches"}->[0]->{"result"} <=> $a->{"matches"}->[0]->{"result"} } @massmatches
		if ($sortby eq "Match Percentage (descending)");
	@precmatches = sort { $a->{"dta"} cmp $b->{"dta"} } @precmatches
		if ($sortby eq "DTA Name");
	@precmatches = sort { $a->{"prec"} <=> $b->{"prec"} } @precmatches
		if ($sortby eq "DTA Mass (ascending)");
	@precmatches = sort { $b->{"prec"} <=> $a->{"prec"} } @precmatches
		if ($sortby eq "DTA Mass (descending)");
	@precmatches = sort { $a->{"matches"}->[0]->{"result"} <=> $b->{"matches"}->[0]->{"result"} } @precmatches
		if ($sortby eq "Match Percentage (ascending)");
	@precmatches = sort { $b->{"matches"}->[0]->{"result"} <=> $a->{"matches"}->[0]->{"result"} } @precmatches
		if ($sortby eq "Match Percentage (descending)");
	

	# display input parameters
	$refdir_string = join "<br>", map scalar(&get_fancyname($_)), @refdirs;
	my $dtavcr_checked = ($DEFS_IONQUEST{"DTA VCR on Selected"} eq "yes") ? " checked" : "";
	my $best_only_checked = ($DEFS_IONQUEST{"Best matching only"} eq "yes") ? " checked" : "";

	# Ugly, ugly hack to get rid of the default line break put in by the form tag
	print qq(<table><td><form action="$ourname" method="post"></td><table></table></table>);
	if ($show_all) {
		print qq(<table cellpadding=0 cellspacing=0 border=0><td><span class="smallheading" style="color:#4040A0"><b>Show:&nbsp;</b></span>);
		print qq(<span class="smalltext">All&nbsp;&nbsp;</span>);
	} else {
		print qq(<table cellpadding=0 cellspacing=0 border=0><td><span class="smallheading" style="color:#4040A0"><b>Show Matches Above:&nbsp;</b></span>);
		print qq(<span class="smalltext">$display_threshold\%&nbsp;&nbsp;</span>);
	}
	print qq(<span class="smallheading" style="color:#4040A0"><b>Select Matches Above:&nbsp;</b></span>);
	print qq(<span class="smalltext">$reqmatch\%</span>);
	
	if ($reqmatch == $DEFS_IONQUEST{"Percent Match Threshold"})
	{
		print qq(<span class="smalltext" style="color:#808080">(Default)</span>);
	}

	print qq(<span class="smallheading" style="color:#4040A0">&nbsp;&nbsp;<b>Tolerance:&nbsp;</b></span>);
	print qq(<span class="smalltext">+/-$tolerance Da&nbsp;&nbsp;</span>);
	print qq(<span class="smallheading" style="color:#4040A0"><b>Sort:&nbsp;</b></span>);
	print qq(<span class="smalltext">$sortby</span></td></table>);
	print qq(<span class="smalltext"><br></span>\n);


	# output table of DTAs to delete
	if (@massmatches || @precmatches)
	{
		&load_java_checkboxes();
		print <<EOF;

<table cellpadding=0 cellspacing=2 border=0>
<tr>
	<td>
	<span class="smallheading">Select:</span>
	</td>
	<td>
	<input type=button CLASS=button value="  All  " onClick="checkAll()">&nbsp;
	<input type=button CLASS=button value="None" onClick="uncheckAll()">&nbsp;
	<input type=button CLASS=button value=" Inv " onClick="invertAll()">&nbsp;
	<input type=reset CLASS=button value="Default"></td>
	<td><span valign="middle" class="normaltext">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="$webhelpdir/help_$ourshortname\_table.html">Help</a>
	&nbsp;&nbsp;&nbsp;&nbsp;</span>
	</td>
	<td>
		<a href="javascript:openDTA_VCR()" onMouseover="status=''; return true" ><image src="$webimagedir/DTA_VCR.gif" height=25 width=60 border=0 ALIGN="left" VALIGN="bottom" ALT="DTA VCR" TITLE="Open DTA VCR window"></a>
	</td>
	<td><input type=checkbox name="dtavcr_show_selected"$dtavcr_checked></td>
	<td><span class="smallheading">DTA VCR on Selected</span></td>
	<td><input type=checkbox name="best_only"$best_only_checked></td>
	<td><span class="smallheading">best matching only</span></td>
	<td><span class="smallheading">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Selected Files:</span></td>
	<td>
		<input type=button CLASS=button value="Delete" onClick="warning2()">&nbsp;
		<input type=button CLASS=button value="Write List" onClick="updateText()">
	</td>
</tr></table>

<input type=hidden name="quick_delete" value="1">
<input type=hidden name="should_delete" value="0">
<input type=hidden name="refdir" value="$refdirs">
<input type=hidden name="directory" value="$dir">
<input type=hidden name="percentage" value="$reqmatch">
<input type=hidden name="tolerance" value="$tolerance">
<input type=hidden name="update_text" value="0">
<input type=hidden name="DTAVCR:conserve_space" value="1">
<input type=hidden name="DTAVCR:include_array" value="selected">
<input type=hidden name="selected" value="">

<input type=hidden name="show_best_only" value="">

<span class="smalltext"><br></span>
EOF
	}

    
	if (@massmatches) {
		my $header_ext = ($filter eq "muquest") ? " / XCorr" : "";
		# 6/13/00 P.Djeu -- See comment at the top of this function.
		print <<EOF;

<table border=5 cellpadding=0 cellspacing=0>
<tr>
	<td align="center"><span class="smallheading">Dir: <a href="$webseqdir/$dir" target="_blank" title="View Directory Listing">$fancyname</a></span></td>
	<td align="center"><span class="smallheading">MH+</span></td>
	<td align="center"><span class="smallheading">\%$header_ext</span></td>
EOF
		if ($filter eq "both") {
			print qq(<td align="center"><span class="smallheading">\% / XCorr</span></td>\n);
		}
		print <<EOF;
	<td align="center"><span class="smallheading">MH+</span></td>
	<td align="center"><span class="smallheading">RefDir: <a href="$webseqdir/$refdirs" target="_blank" title="View Directory Listing">$refdir_string</a></span></td>
</tr>
EOF

		&show_matches_mass();
		print "<span class=\"smalltext\"><br></span>";
	}

	# This dummy form element is used as a divisor between the two tables.  When iterating through the form elements,
	# the appearance of this element can be used to determine if you are in the mass or precursor table
	print qq(<input type=hidden name="tablebreak" value="">\n);

	if (@precmatches) {
		my $header_ext = ($filter eq "muquest") ? " / XCorr" : "";
		# 6/13/00 P.Djeu -- See comment at the top of this function.
		print <<EOF;

<table border=5 cellpadding=0 cellspacing=0>
<tr>
	<td align="center"><span class="smallheading">Dir: <a href="$webseqdir/$dir" target="_blank" title="View Directory Listing">$fancyname</a></span></td>
	<td align="center"><span class="smallheading">Prec</span></td>
	<td align="center"><span class="smallheading">\%$header_ext</span></td>
EOF
		if ($filter eq "both") {
			print qq(<td align="center"><span class="smallheading">\% / XCorr</span></td>\n);
		}
		print <<EOF;
	<td align="center"><span class="smallheading">Prec</span></td>
	<td align="center"><span class="smallheading">RefDir: <a href="$webseqdir/$refdirs" target="_blank" title="View Directory Listing">$refdir_string</a></span></td>
</tr>
EOF

		&show_match_prec();
	}

	# Updated 8/11/00 P. Djeu
	# Write to logfile, this portion of code assumes only 1 ref dir is specified, if more than 1, then this will need
	# to be changed
	open (DTA_TXT, ">$seqdir/$dir/$ionquestlog") or &error("Unable to open $ionquestlog for writing: $!\n");
	print DTA_TXT "Sample Dir: $dir\n";
	print DTA_TXT "Ref Dir: $refdirs\n\n";
	
	# Basic algorithm: cycle through all keys.  If the corrsponding entry from the other table has a better match, do nothing.
	# If the corresponding entry in the other table is a lower match (or doesn't exist), write to the file.
	my ($curr_dta, $dta_tab1, $dta_tab2, $dta_info1, $dta_info2, $refdta1, $refdta2, $match1, $match2);
	foreach $dta_tab1 (sort keys %dtas_to_write) {
		if ($dta_tab1 =~ /mass$/) {
			($dta_tab2 = $dta_tab1) =~ s/mass$/prec/;
		} else {
			($dta_tab2 = $dta_tab1) =~ s/prec$/mass/;
		}
		$dta_info1 = $dtas_to_write{$dta_tab1};
		$dta_info2 = $dtas_to_write{$dta_tab2};
		if (!$dta_info2) {
			# $dta_tab1 is the only entry, so it is okay to write it
			($curr_dta) = split /,/, $dta_tab1;
			($refdta1, $match1,$inten1, $inten2) = ($dta_info1 =~ /^(.+),(\d+),(\d+),(\d+)$/);
			print DTA_TXT "$curr_dta\t$refdta1\t$inten1\t$inten2\n";
		} else {
			# Check which is the better match between $dta_tab1 and $dta_tab2
			($refdta1, $match1,$inten1, $inten2) = ($dta_info1 =~ /^(.+),(\d+),(\d+),(\d+)$/);
			($refdta2, $match2,$inten3, $inten4) = ($dta_info2 =~ /^(.+),(\d+),(\d+),(\d+)$/);
			if ($match1 >= $match2) {
				# Current key has the better match, so write it
				($curr_dta) = split /,/, $dta_tab1;
				print DTA_TXT "$curr_dta\t$refdta1\t$inten1\t$inten2\n";
			} else {
				# Current key is the lesser match, so ignore it
			}
		}
	}
	close DTA_TXT;

	# Continue loading Javascript functions, loaded after the table(s) because the table links are used in this function
	&dta_vcr_code();

	if (@massmatches || @precmatches) {
		print "</form>";
	}
	else
	{
		print "<BR><span class=\"normaltext\"><b>No matches found.</b></span></form><p>\n";
	}

	print <<EOF;
<p>&nbsp;</p>
</body></html>
EOF
	exit 0;

}

###########################         End Table Display code     ############################################################


# Args:
# fulloutfile - Full pathname of the dta file, for instance "$seqdir/$dir/$dta_name"
#
# Finds and returns the first peptide sequence in the .out file, if it exists.  If found,
# the sequence is returned.  If not, "0" is returned.
#
# Basic algorithm: find the peptide sequence based on blank lines...
# 1. Get rid of first blank line (first line of .out file), and look for second one.
# 2. Read in the remaining header of 2 lines:
#     #   Rank/Sp  (M+H)+    Cn    deltCn  C*10^4    Sp     Ions  Reference        Peptide
#    ---  -------  ------  ------  ------  ------   ----    ----  ---------        -------
#
#				OR
#
#     #   Rank/Sp    (M+H)+   deltCn   XCorr    Sp     Ions  Reference                              Peptide
#    ---  -------  ---------  ------  ------   ----    ----  ---------                              -------
#
# 3. Read the next line for the first protein sequence, which is the last "word" at the end

sub get_peptide_sequence {
	my $fulloutfile = $_[0];
	my ($line, $pep_seq);
	$pep_seq = "0";
	#chdir "$local_dir" || &error("Directory $local_dir inaccessible.<P>$!");

	if (-e "$fulloutfile") {
		open (OUTFILE, "$fulloutfile") or &error("Cannot open .out file: $!\n");

		$line = <OUTFILE>;		# First blank line
		while ($line = <OUTFILE>) {
			if ($line =~ /^\s*$/) {	# Second blank line
				last;
			}
		}				
				
		# Error check in case the file is empty
		if (defined $line) {
			# Get rid of header, get to first line with the peptide sequence
			$line = <OUTFILE>;
			$line = <OUTFILE>;
			$line = <OUTFILE>;
					
			#extract last word from the line; this is (hopefully) the sequence
			($pep_seq) = ( $line =~ /.*\s(\S*)\n$/ );
		}
		close OUTFILE;
	}
	return $pep_seq;
}


# Uses the 'delete' form value to determine what was checked, then looks at hidden form elements to find the dta pairs
sub do_update_text
{	
	$dir = $FORM{"directory"};
	$refdir = $FORM{"refdir"};
	my ($curr_dta, $dta_tab1, $dta_tab2, $dta_info1, $dta_info2, $refdta1, $refdta2, $match1, $match2);

	chdir "$seqdir/$dir" or (&MS_pages_header("IonQuest","4040A0"), &error("Unable to open $dir: $!"));
	open (DTA_TXT, ">$ionquestlog") or (&MS_pages_header("IonQuest","4040A0"), &error("Unable to open $ionquestlog for writing: $!\n"));
	# Write header
	print DTA_TXT "Sample Dir: $dir\n";
	print DTA_TXT "Ref Dir: $refdir\n\n";

	foreach $curr_dta (keys %FORM) {
		if (($FORM{$curr_dta} =~ /delete/)) {
			# Retrieve the two relevant form elements
			$dta_info2 = "";
			$dta_info1 = $FORM{"$curr_dta,mass"};
			if ($dta_info1) {		# If mass entry is defined, try to fill in prec entry
				$dta_info2 = $FORM{"$curr_dta,prec"};
				if ($dta_info2) {	# Both entries exist, so need to do comparison to see which one is better
					($refdta1, $match1) = ($dta_info1 =~ /^(.+),(\d+)$/);
					($refdta2, $match2) = ($dta_info2 =~ /^(.+),(\d+)$/);
					if ($match1 >= $match2) {
						# Do nothing, refdta1 is going to get written
					} else {
						# Switch refdta2 to refdta1 so it can get printed
						$refdta1 = $refdta2;
					}
				} else {			# Mass entry must be the only one, okay to print
					($refdta1, $match1) = ($dta_info1 =~ /^(.+),(\d+)$/);
				}
			} else {				# Prec entry must be the only one, okay to print
				$dta_info1 = $FORM{"$curr_dta,prec"};
				($refdta1, $match1) = ($dta_info1 =~ /^(.+),(\d+)$/);
			}
			print DTA_TXT "$curr_dta\t$refdta1\n";
		}
	}
	close DTA_TXT;

	&no_content;	# Keep browser on the same page

	exit 0;
}


sub quick_delete
{
	print "<P>";
	chdir "$seqdir/$dir" or &error("Unable to open $dir: $!");

	@todelete = ();
	foreach $filename (keys %FORM) {
		push(@todelete,$filename) if (($FORM{$filename} =~ /delete/) && !(grep /^$filename$/,  @todelete));
	}
	&do_delete(@todelete);
}


sub delete_matches
{
	print "<P>";
	@todelete = ();

	foreach $matchinforef (@massmatches,@precmatches)
	{
		%matchinfo = %$matchinforef;
		$dta = $matchinfo{"dta"};
		$bestmatch = $matchinfo{"matches"}->[0]->{"result"};
		if ($bestmatch >= $reqmatch) {
			push(@todelete,$dta) unless (grep /^$dta$/, @todelete);
		}
	}

	&do_delete(@todelete);
}


sub do_delete
{
	my @todelete = @_;
	@deleted = ();

	foreach $dtafile (@todelete)
	{
		# find all related files in the directory
		@filestodelete = &find_related($dtafile);

		foreach $filename (@filestodelete)
		{
			if (!(grep /^$filename$/, @deleted)) {  # if not already deleted
				push(@deleted,$filename);
#				(&delete_files("$filename")) || &error("Cannot delete $filename<P>$!");
				&delete_files("$filename");	# fail silently because the programmer is lazy today
			}
		}
		@deleted = sort {$a cmp $b} @deleted;		# just to make the output look better
		&update_selected_dtas($dir);
	}

	# write to the directory log (added cmw,7-24-98)
	$logentry = "IonQuest refdir=$refdirs   mass tolerance=$tolerance  threshold=$reqmatch%  " . localtime() . "  $operator  " .  scalar(@todelete) . " DTA-sets (DTAs+ZTAs+OUTs) deleted";
	&write_deletionlog($dir,$logentry,\@deleted);

	my %dtasetnames, $dtasetname;
	foreach $dtasetname (@todelete) {
		$dtasetname =~ /(.*)\.\d\.dta/;
		$dtasetnames{$1} = 1;
	}
	# output list of deleted files
	$numsetsdeleted = scalar(keys %dtasetnames);
	
	$numdeleted = @deleted;
	print <<EOF;
<h4>$numsetsdeleted DTA-sets ($numdeleted files) deleted from <a href="$webseqdir/$dir">$dir</a></h4>
EOF
	foreach $filename (@deleted) {
		print "<tt>$filename</tt><br>\n";
	}

	print "</body></html>\n";
	exit 0;

}



sub output_form {
	$sel{$tolerance} = " SELECTED";
	$sel{$sortby} = " SELECTED";
	$checked{"mass"} = " CHECKED" if $comparemass;
	$checked{"prec"} = " CHECKED" if $compareprec;

	$checked{"delete_matches"} = ($delete_matches) ? " CHECKED" : "";
	$checked{"display_table"} = (!$delete_matches) ? " CHECKED" : "";
	
	$checked{"show_all"} = ($show_all) ? " CHECKED" : "";
	$checked{"show_matches"} = (!$show_all) ? " CHECKED" : "";
	
	$defrefdir = $DEFS_IONQUEST{"Reference Directory"};
	
	my $dirheading = &create_table_heading(title => "Directories To Compare");
	my $optionheading = &create_table_heading(title => "Options");
	my $outputheading = &create_table_heading(title => "Output");
	
	&load_java_warning();
  print <<EOF;

<script language=javascript>
	function greyedout(yes) {
		var color = "#999999";
		var disabled = true;
		if (yes == "no") {
			color = ""
			disabled = false;
		}
		var show = document.getElementById("show");
		var sort = document.getElementById("sort");
		var sortby = document.getElementById("sortby");
		var sortoption = document.getElementById("sortoption");
		var threshold = document.getElementById("display_threshold_id");
		show.disabled = disabled;
		sort.disabled = disabled;
		sortby.disabled = disabled;
		threshold.disabled = disabled;
	}
</script>

<FORM ACTION="$ourname" METHOD=post>
<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0>
<tr><td width=60>&nbsp;</td><td valign=top>
<TABLE CELLSPACING=0 CELLPADDING=0 BORDER=0 width=455>
<tr><td>$dirheading</td></tr>	
<tr><td>
<table cellspacing=0 cellpadding=0 width=100% border=0 class=outline>
<tr><td bgcolor=#e8e8fa style="font-size:2">&nbsp;</td><td bgcolor=#f2f2f2 colspan=2 style="font-size:2">&nbsp;</td></tr>
<TR height=30>
	<TD class=title width=115>Compare This Dir:&nbsp;&nbsp;</TD>
EOF

  &get_alldirs;
 
  # make dropbox:
  print ("<TD class=data>&nbsp;&nbsp;<span class=\"dropbox\"><SELECT name=\"directory\">\n");
 
  foreach $directory (@ordered_names) {
    print ("<OPTION VALUE = \"$directory\"".($directory eq $dir ? " SELECTED" : "").">$fancyname{$directory}\n");
  }

  print <<EOM;
			</SELECT></span>&nbsp;</TD></TR>
<TR height=30>
	<TD class=title nowrap width=115>To This Ref Dir:&nbsp;&nbsp;</span></TD>
	<TD class=data><span class="dropbox">&nbsp;&nbsp;<select name="refdir">
EOM
  foreach $directory (@ordered_names) {
	#$selected = ($directory eq $defrefdir) ? " selected" : ""; SDR Added not statement, see below comment
	$selected = (($directory eq $defrefdir) && not ($selected)) ? " selected" : "";
	
	# Added by SDR 11/15/01 to allow qtf to select a different reference directory than the default 
	if ($directory eq $qtfRefDir) {
		$selected = " selected";
	}

#	print qq(<input type=checkbox name="refdir" value="$directory" checked>$fancyname{$directory}<br>);
	print qq(<option value="$directory"$selected>$fancyname{$directory});
  }
 $helplink = &create_link();

  print <<EOM;
</select></span>&nbsp;</TD></TR>
<tr><td bgcolor=#e8e8fa style="font-size:2">&nbsp;</td><td bgcolor=#f2f2f2 colspan=2 style="font-size:2">&nbsp;</td></tr>
</table>
</td></tr>
<tr height=25><td>&nbsp</td></tr>
<tr><td>$optionheading</td></tr>	
<tr><td>
<table cellspacing=0 cellpadding=0 width=100% class=outline border=0>
<tr><td bgcolor=#e8e8fa style="font-size:2">&nbsp;</td><td bgcolor=#f2f2f2 colspan=2 style="font-size:2">&nbsp;</td></tr>
<TR height=23>
<TD class=title width=115 nowrap>Compare By:&nbsp;&nbsp;</TD>
<TD class=data nowrap width=24%>&nbsp;<INPUT TYPE=checkbox NAME="comparemass" VALUE="1"$checked{"mass"}>MH+</td>
<TD class=data nowrap><INPUT TYPE=checkbox NAME="compareprec" VALUE="1"$checked{"prec"}>Precursor</td>
</TR>
<TR height=23>
	<TD class=title nowrap>Tolerance:&nbsp;&nbsp;</span></TD>
	<TD class=data colspan=2>&nbsp;&nbsp;±
		<INPUT TYPE="text" NAME="tolerance" value="$tolerance" maxlength=3 size=3 style="font-size:12">&nbsp;Da</TD></TR>
<TR height=23>
<TD class=title nowrap>&nbsp;&nbsp;Select:&nbsp;&nbsp;</TD>
<TD class=data colspan=2>
&nbsp;&nbsp;Matches >=&nbsp;<input type=text NAME="percentage" size=2 maxlength=2 value=$reqmatch style="font-size:12">%
</TD></TR>
EOM


	print <<EOF;
<tr><td bgcolor=#e8e8fa style="font-size:2">&nbsp;</td><td bgcolor=#f2f2f2 colspan=2 style="font-size:2">&nbsp;</td></tr>
</TABLE></td></tr>  
<tr height=25><td>&nbsp</td></tr>
<tr><td colspan=2>$outputheading</td></tr>	
<tr><td>
<table cellspacing=0 cellpadding=0 width=100% border=0 class=outline>
<tr><td bgcolor=#e8e8fa style="font-size:2">&nbsp;</td><td bgcolor=#f2f2f2 colspan=2 style="font-size:2">&nbsp;</td></tr>
<TR height=23>
<TD class=title width=115>Behavior:&nbsp;&nbsp;</TD>
<TD class=data width=24% nowrap>&nbsp;<input type=radio name="delete_matches" value=0$checked{"display_table"} onclick="greyedout('no')">Display Table</td>
<TD class=data><input type=radio name="delete_matches" value=1$checked{"delete_matches"} onclick="greyedout()">Delete Matches</TD>
</TR>

<!------- new lea 6/7/00 ------------>
<TR height=23 id=show>
<TD class=title>Show:&nbsp;&nbsp;</TD>
<TD class=data nowrap>&nbsp;<input type=radio name="show_all" value=1$checked{"show_all"}>All</td>
<TD class=data><input type=radio name="show_all" value=0$checked{"show_matches"}>Matches >=
<input type=text id="display_threshold_id" name="display_threshold" size=2 maxlength=2 value=$DEFS_IONQUEST{"Matches above %"} style="font-size:12">%
</TD>
</TR>
<TR height=23 id=sortby>
<TD class=title>Sort By:&nbsp;&nbsp;</TD>
<TD class=data colspan=2>&nbsp;&nbsp;<span class="dropbox"><SELECT NAME="sort" style="font-size:11" id=sortoption>
  <OPTION$sel{"DTA Name"}>DTA Name
  <OPTION$sel{"DTA Mass (descending)"}>DTA Mass (descending)
  <OPTION$sel{"DTA Mass (ascending)"}>DTA Mass (ascending)
  <OPTION$sel{"Match Percentage (descending)"}>Match Percentage (descending)
  <OPTION$sel{"Match Percentage (ascending)"}>Match Percentage (ascending)
</SELECT></span></TD></TR>
<tr><td bgcolor=#e8e8fa style="font-size:2">&nbsp;</td><td bgcolor=#f2f2f2 colspan=2 style="font-size:2">&nbsp;</td></tr>
</table>
<TR height=45>
	<TD align=right colspan=2 valign=bottom>
			<INPUT TYPE=button CLASS="outlinebutton button" NAME="compare" VALUE="Compare" onClick="warning()">
				&nbsp;&nbsp;&nbsp;&nbsp;$helplink
	</TD>
</TR></table>
</td></tr></table>

<!-- we need some extra information about the checkboxes (look at the start of the form in sequest_launcher.pl for a fuller explanation) -->
<input type=hidden name="defined_comparemass" value=1>
<input type=hidden name="defined_compareprec" value=1>

<input type=hidden name="compare" value="Compare">
<input type=hidden name="browser" value="">
</FORM>
EOF
	&load_java_get_browser;

	print "</body></html>";
	exit 0;

}


sub find_related
{
	my($dta,$root,@mayberelated,@related,$file,@ztas);
	$dta = shift;

	# find related files for each match, assuming we're already in the right directory
	($root) = ($dta =~ /^(.+?\.\d+)\./);
	opendir (THISDIR, ".");
	@mayberelated = grep /^$root\..+$/, readdir THISDIR;
	closedir THISDIR;

	foreach $file (@mayberelated) {
		push(@related,$file) unless ($file =~ /\.zta$/);
	}

	# there's a separate procedure for finding related ZTAs:
	@ztas = &get_zoomscans(".",$dta);
	push(@related,@ztas);

	return @related;

}

######################
# begin dta_vcr_code #
######################

# This function is adapted from runsummary.pl
# See also load_java_DTA_funcs in the Javascript section for the remainder of the DTA VCR code.
# Creates a popup window using dta_vcr.pl.  The checkbox feature is modeled after the example in
# dta_chromatogram, except this version uses dta_vcr.pl directly rather than imports the code
#
# basic algorithm:
# Write the list of dtas to a temp file and use the standard usage (see dta_vcr.pl)
# Each entry in @dtavcr_infos contains the form variables 'id' and 'tableID', which uniquely identify each
# dta_vcr entry
# The short blurbs of data in @dtavcr_infos each contains a last line that triggers the Javascript function check_box(),
# which handles all of the checkbox details by scanning through all boxes in the main form and looking for 'id';
# these update dynamically through Javascript funcs (see load_java_DTA_funcs)
# The 'DTA VCR on Selected' feature is implemented through the hidden form element 'selected' on the main form, which
# contains a list of all dtas to be displayed.  This list is constructed on the spot when the DTA VCR button is pushed.

sub dta_vcr_code
{
	my $i;
	# create a unique name for the dta_vcr window (includes both pid and start time of this Perl process)
	my $dta_vcr_name = "dtavcr" . $$ . $^T;
	my $linkvalue = join("<DTAVCR>", @dtavcr_links);
	my $infovalue = join("<DTAVCR>", @dtavcr_infos);
	my $includeifvalue = join("<DTAVCR>", @dtavcr_include_ifs);

	# get rid of line breaks
	foreach ($linkvalue, $infovalue, $includeifvalue) {
		s/\n/ /g;
	}

	# modified 10/24/99 to prevent major Javascript and caching problems on large pages:
	# instead of including a huge amount of info in hidden form elements on the page, put it in a temp file
	$vcr_file = "$tempdir/$dta_vcr_name.txt";
	open(VCRFILE, ">$vcr_file");
	print VCRFILE "DTAVCR:link=$linkvalue\n";
	print VCRFILE "DTAVCR:info=$infovalue\n";
	print VCRFILE "DTAVCR:include_if=$includeifvalue\n";
	close VCRFILE;

	# use a hidden form element to tell DTA VCR window where that file is
	print qq(<input type=hidden name="DTAVCR:tempfile" value="$vcr_file">\n);

	&load_java_DTA_funcs($dta_vcr_name);
}

# Added by Georgi 01/22/01 to allow for sending only the best match to DTAVCR. This is achieved through running ionquest again 
# but with parameter FORM{'best_only'} set to 1. Then the DTAVCR tempfile is processed and only the best matches for each file
# are kept in DTAVCR:link

sub best_to_dtavcr
{
	my @file = ();
	my @links = ();
	my $vcr_file_new = "$tempdir/dtavcr" . $$ . $^T;
	my $vcr_file_old = $FORM{'DTAVCR:tempfile'};

	open (VCRFILE, "<$vcr_file_old");
	@file = <VCRFILE>;
		
	for ($i=0; $i <= $#file; $i++)
	{
		chop $file[$i];
		my $line = $file[$i];
		my $comp = "";
		my $new_comp = "";
		@links = ();

		# get line identifier and prepare rest of line
		$line =~ s/^([^=]*?)=//;

		my $label = $1;
		my @list = split("<DTAVCR>", $line);
		
		foreach $ln (@list)
		{
			if ($label eq "DTAVCR:link") {
				$ln =~ m/(.*?)\&/gi;
				$new_comp = $1;
			} elsif ($label eq "DTAVCR:info") {
				# very, very ugly, but no other idea
				$ln =~ m/name\=[\"\']{0,1}\s*id\s*[\"\']{0,1}\s*?value\=[\"\']{0,1}(.*?)[\"\']{0,1}\s*?\>/gi;
				$new_comp = $1;
			} else {
				$new_comp = $ln;
			} 

			if ($comp eq "" or $comp ne $new_comp)
			{
				$comp = $new_comp;
				push @links, $ln;
			}
		}

		if ($label eq "DTAVCR:link") {
			$file[$i] = "DTAVCR:link=";
		} elsif ($label eq "DTAVCR:info") {
			$file[$i] = "DTAVCR:info=";
		} else {
			$file[$i] = "DTAVCR:include_if=";
		}

		$file[$i].= join("<DTAVCR>", @links);				
	}

	close VCRFILE;

	# rewrite the tempfile
	open(VCRFILE, ">$vcr_file_new");

	foreach $line (@file)
	{
		# make sure extra blamk line don't mess things up
		next if ($line eq "\n");

		$line =~ s/^([^=]*?)=//;
		my $value = $line;

		print VCRFILE "$1=$value\n";
	}

	close VCRFILE;	

	# now send everything to DTAVCR

	print <<PAGE;

Content-type: text/html

<html>
<head>
<title>DTA VCR</title>
</head>
</html>
<body onload="document.forms[0].submit()">
<form action="$webcgi/dta_vcr.pl" method=post>
<input type=hidden name=selected value="$FORM{'selected'}">
<input type=hidden name="DTAVCR:include_array" value="$FORM{'DTAVCR:include_array'}">
<input type=hidden name="DTAVCR:tempfile" value="$vcr_file_new">
<input type=hidden name="DTAVCR:conserve_space" value="1">

</form>
</body>
PAGE

exit 0;
}

#######################
# end of dta_vcr_code #
#######################


sub error
{
	print "<h2>Error:</h2>\n";
	print "<b>$_[0]</b>";
	print "</body></html>\n";
	exit 1;
}

sub debug
{
	&MS_pages_header("IonQuest", "000000");
	print "<h2>Error:</h2>\n";
	print "<b>$_[0]</b>";
	print "</body></html>\n";
	exit 1;
}

##! Debugging variable printout tool
sub dv
{
	my $varname = $_[0];
	$varname =~s/\'//g;
	my $varvalue = eval $varname;
	print "$varname: $varvalue <BR>"; 
}


####################################################################################################################################
####################################################################################################################################
# Javascript functions
# For better organization, all javascript functions are grouped here as simple print subroutines.

sub load_java_checkboxes
{
	print <<EOF;
<script language="Javascript">
<!--

function checkAll()
{
	for (i = 0; i < document.forms[0].elements.length; i++)
	{
		elt = document.forms[0].elements[i];
		if (elt.value == "delete")	// elt is a checkbox
		{
			elt.checked = 1;
		}
	}
}

function invertAll()
{
	for (i = 0; i < document.forms[0].elements.length; i++)
	{
		elt = document.forms[0].elements[i];
		if (elt.value == "delete")	// elt is a checkbox
		{
			elt.checked = (elt.checked == true) ? false : true;
		}
	}
}

function uncheckAll()
{
	for (i = 0; i < document.forms[0].elements.length; i++)
	{
		elt = document.forms[0].elements[i];
		if (elt.value == "delete")
		{
			elt.checked = 0;
		}
	}
}

//-->
</script>
EOF
}

# Used in the initial form to warn users if they have selected the Delete Matches option.
sub load_java_warning
{
	print <<EOF;
<script language="Javascript">
<!--
function warning()
{
	var myradio = document.forms[0].delete_matches;
	var warn = false;

	for (i = 0; i < myradio.length; i++) {
		if ((myradio[i].value == 1) && (myradio[i].checked))
			warn = true;
	}
	if (warn) {
		if (confirm("All matching DTAs will be deleted without asking for confirmation.  Are you sure you want to proceed?"))
			document.forms[0].submit();
	} else {
		document.forms[0].submit();
	}
}
//-->
</script>
EOF
}

# Used on the table page to ask users for confirmation before deleting files.
sub load_java_warning2
{
	print <<EOF;
<script language="Javascript">
<!--
function warning2()
{
	if (confirm("Are you sure you want to delete the selected dta's and all of their related files?")) {
		document.forms[0].should_delete.value="1";
		document.forms[0].submit();
	}
}
//-->
</script>
EOF
}

# Used on the table page button "Update Checkboxes" to update the current checkbox state text file, $ionquestlog
sub load_java_update_text
{
	print <<EOF;
<script language="Javascript">
<!--

function updateText()
{
	document.forms[0].update_text.value="1";	// Signal update
	document.forms[0].submit();
	alert("Saving current checkbox state in $webseqdir/$dir/$ionquestlog.");
	document.forms[0].update_text.value="0";	// Restore settings
}

//-->
</script>
EOF

}


# These Javascript functions are adapted from run_summary.pl and dta_chromatogram.pl
# Args: dta_vcr_name - Consists of 'dta_vcr' . $$ . $^T -- or in other words
#                                  'dta_vcr' and processID and basetime concatenated together
sub load_java_DTA_funcs
{
	my $dta_vcr_name = $_[0];
	my $num_dtas = scalar(@dtavcr_links);
	my @temp_arr1 = @dtavcr_links;
	my @temp_arr2 = @dtavcr_infos;
	my $elt1;
	my $elt2;
	$vcr_file = "$tempdir/$dta_vcr_name.txt";

	print <<EOF;
<script language="Javascript">
<!--

// declare reference to DTA-VCR window as a global variable
var dta_vcr_ionquest;

// global index that holds the place of the current form element in Ionquest, updated when DTA VCR shifts to a new dta
var i;

//var jdtavcr_links = new Array($num_dtas);
//var jdtavcr_infos = new Array($num_dtas);

function openDTA_VCR()
{
	if (dta_vcr_ionquest && !dta_vcr_ionquest.closed) {
	
		dta_vcr_ionquest.focus();

	} else {
		var table = 1;		// A table flag, represents whether we are in table 1 or 2
		var num_elts = document.forms[0].elements.length;
		document.forms[0].selected.value = "";

		if (document.forms[0].dtavcr_show_selected.checked) {
			// Make a list of all selected dtas			
			for (i = 0; i < num_elts; i++) {
				if (document.forms[0].elements[i].name == "tablebreak") {
					table = 2;
					continue;
				}
				
				if ((document.forms[0].elements[i].value == "delete") && (document.forms[0].elements[i].checked)) {
					// Distinguish between the two tables
					document.forms[0].selected.value += (table == 1) ?  (", " + document.forms[0].elements[i].name + "_mass") : (", " + document.forms[0].elements[i].name + "_prec");
				}
			}

		} else {	// Checkbox not checked; show everything			
			// Select all files
			for (i = 0; i < num_elts; i++) {
				if (document.forms[0].elements[i].name == "tablebreak") {
					table = 2;
					continue;
				}

				if (document.forms[0].elements[i].value == "delete") {
					// Distinguish between the two tables
					document.forms[0].selected.value += (table == 1) ?  (", " + document.forms[0].elements[i].name + "_mass") : (", " + document.forms[0].elements[i].name + "_prec");
				}
			}
		}
		
		oldaction = document.forms[0].action;
		oldtarget = document.forms[0].target;
		
		if (document.forms[0].best_only.checked == true) 
		{
			document.forms[0].show_best_only.value = 1;
			document.forms[0].action="$ourname"
		}
		else
		{
			document.forms[0].show_best_only.value = 0;
			document.forms[0].action="$webcgi/dta_vcr.pl";
		}

		document.forms[0].target="$dta_vcr_name";


		self.onfocus = DTA_VCR_cleanup;

		dta_vcr_ionquest = open("javascript:opener.document.forms[0].submit()","$dta_vcr_name", "resizable");
	}
}

// After DTA VCR window is opened, restore settings
function DTA_VCR_cleanup()
{
	// put things back as they were
	document.forms[0].action = oldaction;
	document.forms[0].target = oldtarget;
	self.onfocus = null;
}


// Initializes checkbox state/event handlers when a dta is loaded in DTA VCR, this function is called via
// a snipet of code in \@dtavcr_infos
function check_box()
{
	var vcr_dta;
	var num_elts = document.forms[0].elements.length;

	vcr_dta = dta_vcr_ionquest.middleframe.infoframe.document.forms[0].id.value;


	// Form elements are poorly named (leading numbers and dots galore) so instead of being able to access form
	// elements directly, must loop through all elements looking for the correct match

	// If element is in first table, search fowards to prevent multi-table bug
	if (dta_vcr_ionquest.middleframe.infoframe.document.forms[0].tableID.value == "mass") {
		for (i = 0; i < num_elts; i++) {
			if(document.forms[0].elements[i].name == vcr_dta) {
				break;
			}
			// If element is not found, fail silently
		}
	}

	// If element is in second table, search backwards to prevent multi-table bug
	if (dta_vcr_ionquest.middleframe.infoframe.document.forms[0].tableID.value == "prec") {
		for (i = (num_elts - 1); i >= 0; i--) {
			if(document.forms[0].elements[i].name == vcr_dta) {
				break;
			}
			// If element is not found, fail silently
		}
	}


	dta_vcr_ionquest.middleframe.infoframe.document.forms[0].box.checked = document.forms[0].elements[i].checked;
	dta_vcr_ionquest.middleframe.infoframe.document.forms[0].box.onclick = update_main_checkbox;
}

// if you check or uncheck the checkbox in dta_vcr, make sure the changes are registered in ionquest
function update_main_checkbox()
{
	document.forms[0].elements[i].checked = dta_vcr_ionquest.middleframe.infoframe.document.forms[0].box.checked;
}


// close DTA VCR window if main window is changed
function close_popups()
{
	if (dta_vcr_ionquest)
		if (!dta_vcr_ionquest.closed)
			dta_vcr_ionquest.close();
}
onunload = close_popups;

//-->
</script>
EOF
}

# Get the type of browser for Perl use via a form element
sub	load_java_get_browser
{
print <<EOF;
<script language="Javascript">
<!--
if (isIE) {
	document.forms[0].browser.value = "IE";
}
//-->
</script>
EOF
}


# When page is loaded, gets rid of the progress bar
sub load_java_toggle_progress
{
print <<EOF;
<script language="Javascript">
<!--
function toggle_progress() {
	document.all.progress.innerHTML ="";
}
// Netscape does not support the innerHTML element, so this only works on IE currently.
onload = toggle_progress;

//-->
</script>
EOF
}

#
# findReferenceDirectory
#
# given a directory, find the directory generated by the previous run (based on
# run #) on the same instrument
#
sub getReferenceDirectory
{
	my ($runNumber, $runName, $firstName, $lastName, $sampleID);
	my ($dir, $directDirName);
	my ($sql, $err);
	my $dbalreadyopen=0;
	my $resultDir;
	my $directory = shift;

	if (!$DB) {
		die "Couldn't open database!" unless (!useDB());
	} else {
		$dbalreadyopen = 1;
	}

	# read in sampleList once for getDirs later
	readInFlatFile();
	
	# get the runs
	$sql = qq(SELECT TOP $MAX_RUNS_TO_SKIP tblRunLog.fldRunNumber, tblRunLog.fldOperator, tblRunLog.fldSampleRun, tblRunLog.fldDate, tblRunLog.fldInstrument, tblRunLog.fldSampleID, Users.FirstName, Users.LastName FROM (tblRunLog LEFT JOIN Samples ON tblRunLog.fldSampleID = Samples.SampleID) LEFT JOIN Users ON Samples.UserID = Users.UserID WHERE (((tblRunLog.fldRunNumber) < '$runNumberHash{$directory}') AND (tblRunLog.fldInstrument = (SELECT fldInstrument FROM tblRunLog WHERE fldRunNumber = '$runNumberHash{$directory}')) AND ((tblRunLog.fldService)='HPLC' Or (tblRunLog.fldService)='LCMS' Or (tblRunLog.fldService)='ESI')) ORDER BY tblRunLog.fldDate DESC , tblRunLog.fldRunNumber DESC;);

	if(($err = $DB->Sql($sql))) {
		&error("Error querying the database.", $err, $DB->Error(), $sql);
	}


	while($DB->FetchRow()) {
		($runNumber, $runName, $firstName, $lastName, $sampleID) =
			$DB->Data("fldRunNumber", "fldSampleRun", "FirstName", "LastName", "fldSampleID");
		
		$directDirName = substr($firstName, 0, 1) . $lastName . $runName;	
		$directDirName =~ tr/A-Z/a-z/;
		$directDirName =~ tr/a-z0-9_-//cd;
		$dir = &getDirs($directDirName, $sampleID, $runNumber);

		if($dir ne "") { 
			$resultDir = $directDirName;
			last;
		}
	}

	if (!$dbalreadyopen) {
		$DB->Close();
	}

	return $resultDir;
}

###########################
## read SAMPLELIST file into global variables to be used by getDirs
sub readInFlatFile
{
    my (%entry, $line, @names, @info, $i, $d);

	if (open (SLIST, "$SAMPLELIST")) {
        $line = <SLIST>;
        chomp $line;
        $line =~ tr/A-Z/a-z/;
        @names = split (/:/, $line);

        while ($line = <SLIST>) {
			chomp $line;
			%entry = ();
            @info = split (/:/, $line);
            for ($i = 0; $i <= $#names; $i++) {
                $entry{$names[$i]} = $info[$i];
            }
            $d = $entry{"directory"};
            $sampleIDHash{$d} = $entry{"sampleid"};
            $runNumberHash{$d} = $entry{"runnumber"};
        }
        close SLIST;
    }
	@allDirs = keys %sampleIDHash;

	## because SAMPLELIST actually isn't perfect, let's look at all directories too;
	## won't have sampleID and runNumber for these (probably too slow, maybe not), but it will still
	## be useful for matching directory name directly
    opendir (SEQDIR, $seqdir) || die ("can't open Sequest dir");
    foreach $d (readdir (SEQDIR)) {
		push(@allDirs, $d)  unless exists($sampleIDHash{$d});
    }
    closedir SEQDIR;

	@allDirs = sort @allDirs;
}

sub getDirs 
{
	my ($directDirName, $runNumber, $sampleID);
	my ($dir, $dirList, $dirList2, $temp);

	$directDirName = shift;
	$sampleID = shift;
	$runNumber = shift;
	
	## get dir matching $directDirName if such exists, plus all dirs corresponding to given sampleID
	foreach $dir (@allDirs) {
		if($dir eq $directDirName || $sampleIDHash{$dir} == $sampleID) {
			## separate those that also match runNumber (or match $directDirName)
			$temp = "<a href='$webcgi/runsummary.pl?directory=$dir&sort=consensus' target='_blank'>$dir</a>";
			
			if(!exists($runNumberHash{$dir})) {
				## must have come from listing of directories
				$temp .= '(not in SAMPLELIST)';
			} elsif($runNumberHash{$dir} ne '' && $runNumberHash{$dir} !~ m/^[A-Z]\d+$/) {
				## corrupted runNumbers
				$temp .= '(bad runNumber)';
			} elsif($runNumberHash{$dir} ne $runNumber) {
				$temp .= "(<a href='lcq_prelude.pl?action=showRunInfo&runNumber=$runNumberHash{$dir}&noEdit=true' target='_blank'>"
					  .  "<span class='smalltext'>$runNumberHash{$dir}</span></a>)";
			}

			if($runNumberHash{$dir} eq $runNumber || $dir eq $directDirName) {
				$dirList .= "$temp<br>\n";
			} elsif($sampleID != 0) {		## don't include *just* sampleID match for sampleID 0
				$dirList2 .= "&nbsp;&nbsp;&nbsp;&nbsp;$temp<br>\n";
			}
		}
	}
	return $dirList.$dirList2;
}